Task3
December11/Task2 pull request #2
Opened 2022-07-22 13:38 UTC by December11

2022-07-26 09:26 UTC, evgeniyCache requested changes

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/DetailViewController.swift
> +        switch indexPath.row {
вот тут надо обращаться к viewItem.type и делать switch)

лучше быть привязанным к моделям, тк сейчас если ты добавишь ещё одну ячейку тебе везде придётся менять) и если тут в cellForRowAt оно и ок, то в numberOfRowsInSection должно всё заработать без изменений)

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/DetailViewController.swift
> +        200.0
в константы, чтобы дать консистентное название

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/SectionViewController.swift
> +        let fetchService = FetchedDataService(.news)
каждое нажатие не стоит создавать сервис. В сервисе должно быть несколько методов, тут например service.loadNews
выше
service.loadBooks

а сам service должен быть создан единожды в ините

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/SectionViewController.swift
> +
много \n

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/SectionViewController.swift
> +        let dispatchGroup = DispatchGroup()
выглядит так, что группа должна быть внутри сервиса, а не во viewController. Там он сделает логику merge двух запросов и дернет один раз completion

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/SectionViewController.swift
> +        let bookFetchWorkItem: DispatchWorkItem
что-то мудрёно, у нас же есть queue, они могут быть параллельными, также есть барьер, который позволит решить проблему писателей и читателей. Надо сделать будет так)

DispatchWorkItem + DispatchGroup выглядит дженериком прям)

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/SectionViewController.swift
> +            items.append(contentsOf: books)
если добавиться ещё одна сущность, то придётся ещё один массив создавать и тут добавлять через items.append, что кажется не очень. Но поправив коммент выше - это уйдёт)

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/SectionViewController.swift
> +        Constants.buttonTitles.count
return in func

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/SectionViewController.swift
> +    private func fetchData(
тебе надо вынести код с 69 по 78 строчку в отдельный метод, чтобы был updateUI(with: completion, sender: sender).

Сверху ты будешь прям обращаться service.fetch { [weak self]
 self?.updateUI(with: completion, sender: sender] 
}

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/SectionViewController.swift
> +                DispatchQueue.main.async {
очень странно, что при ошибки, мы переходим на мейн поток, а при удачном кейсе нет

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/SectionViewController.swift
> +        switch indexPath.row {
сложна. вся настройка кнопки должна быть в разном методе, мануально. configureRandomButton() configureShuffleButton() и тд.

Сейчас я должен буду не забыть сюда добавить addTarget, если сделаю ещё одну кнопку. А компилятор мне никак это не подсветит. Плюс я могу добавить и не сюда, а там где настраиваю вьюшку и мы получим рассинхрон. Потому давай устанавливать мануально в каждом методе, либо хотя бы во viewDidLoad, разделяя \n (если там всего две строчки конфигурации у кнопки)

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Presentation/Main/View/ButtonWithLoader.swift
> +    var isCancelled = false
если я поменяю это поле извне, ничего не будет происходить внутри, также оно внутри не меняется, не очень понимаю зачем нам это поле

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Presentation/Main/View/ButtonWithLoader.swift
> +
много \n

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Protocols/FetchedDataProtocol.swift
> +protocol FetchedDataProtocol {
не стоит связывать сущности DTO слоёв. Если у тебя твои модели для вьюшек, то ок.

Тк сейчас придут и попросят для ручки books добавить ещё поле pageNumbers

тебе придётся менять для сущности news и ВЕЗДЕ где она используется добавлять эти pageNumbers.

Потому сервис должен возвращать либо BooksDTO либо NewsDTO (и всё)

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Services/FetchedDataService.swift
> +        static var bookNetworkService: NetworkService<BookDTO> {
какой-то жесткий enum, где при разных кейсах я могу получить информацию и разных сервисах, которые статичные.

Пример. Я сейчас могу из любого файла, достать FetchedDataService.Service. bookNetworkService или ещё какой сервис. Так нельзя.

Мы делаем сервисы чтобы они инкапсулировали логику и были максимально закрытыми. у тебя у сервиса должно быть три интерфейса loadBooks/loadNews/loadShuffle (в последнем ты бы использовала параллелизацию). Весь сервис можно было бы ещё закрыть протоколом, где были бы только эти три интерфейса, а всё остальное закрытое внутри

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Services/FetchedDataService.swift
> +            fetchBooks { result in
из-за enum подхода, каждый новый кейс увеличит на 8 строчек моментально, а если там ещё будут какие-то проверки, то и более)

2022-07-26 09:26 UTC, evgeniyCache commented on Task2/Task2/Services/NetworkService.swift
> +final class NetworkService<TypeDTO: Decodable> {
тебе не нужно знать тип generic DTO в момент создания сервиса, это же можно делать в момент запроса по методу fetch)

2022-07-27 07:44 UTC, December11 commented on Task2/Task2/Models/Book.swift
> +final class Book: FetchedDataProtocol {
вообще не знаю зачем я его сделала классом)) подумала, что раз добавляю инит в протоколе, то можно и делать его классом. Но переделаю на структуру обратно, да. 
Мне часто сложно бывает понять лучше делать структуру или класс.

2022-07-27 07:47 UTC, December11 commented on Task2/Task2/Models/DTO/ItemsDTO.swift
> +struct ItemsDTO<TypeDTO: Decodable>: Decodable {
о, окей) тогда сделаю отдельные структуры. А можешь привести пример переиспользуемого DTO, который для сущностей) и вообще - как понять когда можно переиспользовать, а когда не стоит? Или список/массив и есть показатель что нужно делать отдельно?

2022-07-27 07:48 UTC, December11 commented on Task2/Task2/Models/DTO/NewsDTO.swift
> +
окей, уберу везде. Значит по код стайлу только сверху \n ?

2022-07-27 07:50 UTC, December11 commented on Task2/Task2/Models/DTO/NewsDTO.swift
> +//  Created by Alla Shkolnik on 16.07.2022.
а кстати, помню у нас была даже такая проблема что какое-то поле не пришло с бэка, хотя было помечено как обязательное) толи номер машины, толи еще что) 

но окей, это ведь обычно в спеке от бэка прописано, что обязательное, а что нет. Тогда... просмотрю и сделаю часть полей обязательными.

2022-07-27 07:56 UTC, December11 commented on Task2/Task2/Presentation/Library/View/ContentListTableViewCell.swift
> +
о, точно надо же обновить ячейки в таблице.
Я кстати раньше делала это просто обнуляя все переменные в самом начале метода configure в самой ячейке. Но кажется нагляднее использовать именно prepareForReuse(), видимо он как раз для этого, да?)

2022-07-27 07:58 UTC, December11 commented on Task2/Task2/Presentation/Library/View/ContentListTableViewCell.swift
> +            make.trailing.lessThanOrEqualTo(infoButton.snp.leading).inset(-Constants.defaultSideInsets)
ну вообще - вот ровно так и есть) стеквью начинает расширяться и сплющивать кнопку-иконку. Пробовала полечить это приоритетом, но почему-то не помогло( Мне было интересно - можно ли как-то иначе это обходить) или в целом, делать less - норм.

2022-07-27 08:01 UTC, December11 commented on Task2/Task2/Presentation/Library/View/DetailHeaderTableView.swift
> +    func configure(imageString: String) {
хм, а где лучше делать превращение string в URL ? в самой ячейке таблицы, получается? И почему плохо делать это уже в ячейке? это отнимает время на преобразование?

2022-07-27 08:02 UTC, December11 commented on Task2/Task2/Presentation/Library/View/DetailHeaderTableView.swift
> +        coverImageView.contentMode = .scaleAspectFill
а, вот и ответ, видимо)) окей!

2022-07-27 08:06 UTC, December11 commented on Task2/Task2/Presentation/Library/ViewControllers/ContentListViewController.swift
> +    var content = [FetchedDataProtocol]()
окей, получается, лучше всегда делать private свойства.  А когда стоит делать именно неприватные свойства?

2022-07-27 08:20 UTC, December11 commented on Task2/Task2/Presentation/Library/ViewControllers/ContentListViewController.swift
> +        Constants.cellHeight
а моя константа как раз не прочерти?) 

кстати хотела спросить, у меня где-то был пример где много констант, где пара инсетов, пара тайтлов
`private enum Constants {
        static let infoImageTitle = "info.circle"
        
        static let infoButtonWidth = 24.0
        static let coverWidth = 108.0
        static let separatorHeight = 1 / UIScreen.main.nativeScale
        
        static let defaultSideInsets = 16.0
        static let smallSideInsets = 8.0
        static let labelSpacing = 2.0
    }`

 - лучше для таких случаев делать один` enum Constants {}` или несколько типа `enum Instets {} `,` enum Titles {} ` ?

2022-07-27 08:21 UTC, December11 commented on Task2/Task2/Presentation/Library/ViewControllers/ContentListViewController.swift
> +        let currentItem = content[indexPath.row]
а, это чтобы при удалении не было косяков, да(

2022-07-27 08:22 UTC, December11 commented on Task2/Task2/Presentation/Library/ViewControllers/ContentListViewController.swift
> +        tableView.cellForRow(at: indexPath)?.isSelected = false
о, забыла про это свойство) 
в что обычно делают в `didSelectRowAt` и `willSelectRowAt` ?

2022-07-27 08:28 UTC, December11 commented on Task2/Task2/Presentation/Library/ViewControllers/DetailViewController.swift
> +        switch indexPath.row {
хм, у меня кажется вышел довольно странный код - вложенный тип `private enum Cell: Int {
        case header = 0, title, description, footer
    }`
    внутри таблицы, только для того чтобы проверять по порядку что это за viewItem.type грубо-говоря. Надо наверное было делать подобное более верхнеуровнево и проверять именно тип, а не номер строки) 
    Я правильно поняла?)

2022-07-27 08:38 UTC, December11 commented on Task2/Task2/Presentation/Library/ViewControllers/SectionViewController.swift
> +        let bookFetchWorkItem: DispatchWorkItem
хм, окей сделаю тогда очереди и барьер. Ни разу не делала барьер еще))

2022-07-27 08:45 UTC, December11 commented on Task2/Task2/Presentation/Library/ViewControllers/SectionViewController.swift
> +        Constants.buttonTitles.count
мне казалось что внутренний тип, это как бы тоже проперти, но это неправильно) получается, return нужен всегда, кроме проперти, окей.

2022-07-27 08:47 UTC, December11 commented on Task2/Task2/Presentation/Library/ViewControllers/SectionViewController.swift
> +                DispatchQueue.main.async {
хах, да уж) но, надеюсь, я просто обрабатываю это выше. вроде у меня при нотифае обработка в главной очереди. Но такое вообще странно смотрится, да? 


а правильнее вообще-то внутри комплишена у Фетча делать переход на главную очередь, да? чтобы не были эти переходы то там, то сям.

2022-07-27 08:54 UTC, December11 commented on Task2/Task2/Presentation/Library/ViewControllers/SectionViewController.swift
> +        switch indexPath.row {
окей) вообще, вот это у меня раньше было не таблицей, а 4 кнопками со стеквью. Но это казалось чем-то неправильным, много повторений, поэтому переделала на таблицу. Но мне еще сложно понять - когда стоит делать таблицу? 

и еще вопрос, где лучше addTarget добавлять? кажется, уместно куда-то во viewDidLoad, да? он как раз чаще всего один раз загружается.

2022-07-27 08:57 UTC, December11 commented on Task2/Task2/Presentation/Main/View/ButtonWithLoader.swift
> +    var isCancelled = false
ой, это я хотела какую-то проверку добавить, чтобы при нажатии какой-либо из кнопок у меня другие откатывались к начальному состоянию и ничего больше не скачивалось. 
Кажется, в итоге, просто забыла обработать такой кейс 😅 Да и вообще - это видимо надо делать как-то совсем иначе)

2022-07-27 09:11 UTC, December11 commented on Task2/Task2/Services/FetchedDataService.swift
> +        static var bookNetworkService: NetworkService<BookDTO> {
мне пока так сложно думать о том чтобы ограничивать доступ и инкапсулировать, надеюсь, придет с опытом) 
Постараюсь приучить себя думать об этом)

2022-07-27 09:33 UTC, evgeniyCache commented on Task2/Task2/Models/DTO/ItemsDTO.swift
> +struct ItemsDTO<TypeDTO: Decodable>: Decodable {
Например, есть сущность PromocodePayload и она везде одинаковая по проекту и для ресторанов и для магазинов. Но потом приходит бэк и говорит, что для магазинов хочу ещё добавить в эту сущность картинку => тогда надо уже создать свой DTO. Правило простое, если объект одинаков на разных ручках, то можно переиспользовать, если есть различие, которое конфликтует или не подходит для другого флоу или невозможно для другого флоу - то лучше создавать раздельные DTO

2022-07-27 09:33 UTC, evgeniyCache commented on Task2/Task2/Models/DTO/NewsDTO.swift
> +
ага

2022-07-27 09:34 UTC, evgeniyCache commented on Task2/Task2/Models/DTO/NewsDTO.swift
> +//  Created by Alla Shkolnik on 16.07.2022.
да, спеки конечно нет, но наверняка какое-то поле присутствует везде)

2022-07-27 09:36 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/View/ContentListTableViewCell.swift
> +
да, он надежнее) в конфигурации тоже стоит обновлять) я обычно пока не пригодиться не использую prepareForReuse, чтобы не дублировать код в конфигурации. Но бывает конфигурация не завязана, например, на image, который грузится где-то раньше, тогда prepareForReuse обязателен)

2022-07-27 09:38 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/View/ContentListTableViewCell.swift
> +            make.trailing.lessThanOrEqualTo(infoButton.snp.leading).inset(-Constants.defaultSideInsets)
Вообще, stackView удобная вещь, но она не гибкая, просто знай, если тебе нужна будет такая ситуация, то кажется лучше сделать два лейбла просто. Эти контрейнты можно хранить как проперти в объекте Cell, при конфигурации менеджерить (скажем, если есть только title, то сделать titleCenterYConstraint.isActive = true, а другой сделать false

2022-07-27 09:40 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/View/DetailHeaderTableView.swift
> +    func configure(imageString: String) {
плохо, потому что в ячейку и вьюшку (да и вообще в конфигурацию) должны попасть уже готовые данные. 

Если у тебя сейчас эти данные использовать в другой вьюшке, то снова придётся делать URL(). 

Можно делать в vc, можно делать при инициализации из DTO в твою модель

2022-07-27 09:43 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/ContentListViewController.swift
> +    var content = [FetchedDataProtocol]()
вообще редкий кейс, тк контроллеры довольно таки обособленные ребята, и если ты что-то и хочешь туда установить, то это будет установлено один раз, перед показом экрана, до viewDidLoad)

Наверное есть какой-то узкий кейс, когда update нам нужен

2022-07-27 09:44 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/ContentListViewController.swift
> +            cell.separatorView.isHidden = true
да, в ту модель конфигурации добавить let separatorNeeded: Bool

2022-07-27 09:47 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/ContentListViewController.swift
> +        Constants.cellHeight
твоя константа проперти, но используется в методе, потому у нас по кодстайлу пишем return. А если бы это было computed var, то не писали бы)

Вообще если разделение \n кажется тебе неочевидным (то есть в enum очень много разных констант), то делают внутри enum Constants ещё один enum LabelConstants и так разделяют. Но обычно разделение \n хватает между static let, если их правильно группировать

2022-07-27 10:44 UTC, December11 commented on Task2/Task2/Models/DTO/ItemsDTO.swift
> +struct ItemsDTO<TypeDTO: Decodable>: Decodable {
спс)

2022-07-27 10:46 UTC, December11 commented on Task2/Task2/Presentation/Library/View/ContentListTableViewCell.swift
> +
о, получается, мне стоит сделать и там, и там.

2022-07-27 11:06 UTC, December11 commented on Task2/Task2/Presentation/Library/View/ContentListTableViewCell.swift
> +            make.trailing.lessThanOrEqualTo(infoButton.snp.leading).inset(-Constants.defaultSideInsets)
я люблю стеквью в основном потому что в фигме есть прям очень похожая сущность, которая называется авто-лейаут) Это поначалу чуть ломало мне мозг)) 
Но окей, надо бы им пореже пользоваться)

2022-07-27 11:21 UTC, December11 commented on Task2/Task2/Presentation/Library/View/DetailHeaderTableView.swift
> +    func configure(imageString: String) {
а, понятие тупая вьюшка включается себя и отсутствие преобразования строки в ссылку, окей)

2022-07-27 11:22 UTC, December11 commented on Task2/Task2/Presentation/Library/ViewControllers/ContentListViewController.swift
> +    var content = [FetchedDataProtocol]()
окей, тогда буду везде делать приватные свойства, и в крайнем случае уж давать кому-то извне менять. 
Я не помню, а всякие нотификейшены и прочее, они ж и так смогут реагировать если приватная штучка поменялась, да?

2022-07-27 11:24 UTC, December11 commented on Task2/Task2/Presentation/Library/ViewControllers/ContentListViewController.swift
> +        Constants.cellHeight
о, окей, я поняла. кажется, если это выходит какой-то прям совсем большой Ленам, то это уже будет иметь смысл... иначе долго искать просто будет при вызове.

2022-08-05 09:54 UTC, December11 commented on Task2/Task2/Presentation/Color/ViewControllers/ColorViewController.swift
> +            topChildViewController.view.backgroundColor = .randomColors.top
чтобы не было одинаково - генерирую рандомное число и прибавляю/вычитаю его из полуспектра. 
Цвета по идее мало проверять на одинаковость, они же могут быть очень-очень похожи(

2022-08-12 15:27 UTC, evgeniyCache approved these changes

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/View/MainButtonTableViewCell.swift
> +
prepareForReuse, надо удалять removeTarget

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/ContentListViewController.swift
> +        static let cellIdentifier = "ContentListTableViewCell"
его лучше хранить как static let у ячейки

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/ContentListViewController.swift
> +        guard let currentItem = dataSource?.item(at: indexPath.row) else { return UITableViewCell() }
лучше вызвать в самом начале, иначе реюз просто не нужен

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/ContentListViewController.swift
> +        return Constants.cellHeight
высоту тоже лучше в статичной static let у ячейки, а там уже внутри брать из константы

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/ContentListViewController.swift
> +        let details = DetailViewController()
можно создать один раз и вызвать configure()

но, надо быть аккуратным и посмотреть, что deinit вызывается корректно

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/DetailViewController.swift
> +    private enum Constants: CaseIterable {
зачем CaseIterable

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/DetailViewController.swift
> +                return "DetailDescriptionTableViewCell"
но лучше хранить id в проперти static let

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/DetailViewController.swift
> +    private var item: Configuration?
item кажется не нужен

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/DetailViewController.swift
> +        static let height = 200.0
лучше сохранить в элементе, который такой высоты

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/MainButtonViewController.swift
> +    private enum Constants {
константы (либо в самом низу файла) или как nested types выше всех

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/MainButtonViewController.swift
> +        static let identifier = "MainButtonTableViewCell"
перенести в ячейку и в других подобных случаях

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/MainButtonViewController.swift
> +    private let service = MainButtonService()
MainService

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/MainButtonViewController.swift
> +        service.loadBooks { [weak self] result in
лучше накинуть weak sender навсякий

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/MainButtonViewController.swift
> +                guard let self = self else { return }
можно и в самом начале guard let self

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/MainButtonViewController.swift
> +                sender.stopLoadAnimation()
handleError(with error) и использовать во всех таких кейсах

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/MainButtonViewController.swift
> +            switch result {
defer { stopAnimation }

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/MainButtonViewController.swift
> +        let destination = ContentListViewController()
private let один раз можно при ините создать

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/MainButtonViewController.swift
> +        self.navigationController?.pushViewController(destination, animated: true)
self можно убрать

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/MainButtonViewController.swift
> +        let alertController = UIAlertController(title: title, message: message, preferredStyle: .alert)
кажется можно тоже выкинуть в протокол с дефолтной реализацией

2022-08-12 15:27 UTC, evgeniyCache commented on Task2/Task2/Presentation/Library/ViewControllers/MainButtonViewController.swift
> +        Int.random(in: 0...1) == 0 ? loadBooksAndPush(at: sender) : loadNewsAndPush(at: sender)
[loadBooksAndPush(at: sender), loadNewsAndPush(at: sender)].randomElement

2022-08-12 16:51 UTC, merged

2022-08-16 20:25 UTC, December11 commented on Task2/Task2/Presentation/Library/ViewControllers/ContentListViewController.swift
> +        let details = DetailViewController()
решили тут оставить создание при нажатии на кнопку

2022-08-16 20:26 UTC, December11 commented on Task2/Task2/Presentation/Library/ViewControllers/MainButtonViewController.swift
> +        let destination = ContentListViewController()
решили оставить создание по нажатию

2022-08-17 07:57 UTC, December11 commented on Task2/Task2/Presentation/Library/ViewControllers/DetailViewController.swift
> +    private var item: Configuration?
решили заменить его на датасорс, чтобы модалка не хранила данные, которые показывает